# Generated by Django 5.1 on 2024-09-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="cover_image",
            field=models.ImageField(blank=True, upload_to="album_covers/"),
        ),
        migrations.AddField(
            model_name="album",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="album",
            name="genre",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
